application: marcus-profile
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /styles/(.*\.css)
  mime_type: text/css
  static_files: dist/styles/\1
  upload: dist/styles/(.*\.css)

- url: /scripts/(.*\.js)
  mime_type: text/javascript
  static_files: dist/scripts/\1
  upload: dist/scripts/(.*\.js)

- url: /(.*\.html)
  mime_type: text/html
  static_files: dist/\1
  upload: dist/(.*\.html)

skip_files:
- app/bower_components/(.*)
- node_modules/(.*)
